### PR TITLE
Unsupported operation bug fix

### PR DESCRIPTION
**Pull request by zygimantus**
See more at http://stackoverflow.com/a/34678380/1766166

### CODE REVIEW

**Comment by pedrovgs** [comment]
Hi @zygimantus!

I don't understand what's the goal of this PR. Why would you add a ``pom.xml`` file to a project using ``Gradle`` as build tool? You have a link in the PR description but it's related to the http client  and you mention a ``Unsupported Operation bug fix`` in your description.

Could you elaborate the issue you are trying to fix and the main motivation for your changes?

**Comment by zygimantus** [comment]
Hi @pedrovgs !

My mistake that commit 1ee5444 was also added to this PR! I am using your lib in Java web application and it gave the error which is described [here](http://stackoverflow.com/a/34678380/1766166). This commit solved the issue. If you think that you don't need this fix, you can ignore it.

**Comment by pedrovgs** [comment]
Could you please remove the pom file from this PR? This file is not needed at all. Most of the code you've changed has been moved. Could you review your commits and apply just the minimum changes needed to fix the issue? With the current diff, identify where the change is quite difficult.

We will also wait for @flipper83 's review before to merge. He's the main committer in this repository.

Thanks in advance! 😃

**Comment by zygimantus** [comment]
I have added a new [PR](https://github.com/Karumi/MarvelApiClientAndroid/pull/16) where changes are easy to understand.

**Pull request closed without merging**
